In [1]:
import numpy as np

In [3]:
#Задание 1

np.arange(20,0,-1)


array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,
        3,  2,  1])

In [9]:
#Задание 2
x = np.diag(np.arange(10,0,-1), k=0)

In [10]:
x

array([[10,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  9,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  8,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  7,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  6,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  5,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  4,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  3,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  2,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  1]])

In [11]:
sum([sum(item) for item in x])

55

In [27]:
#Задание 3
#4x + 2y + z = 4
#x + 3y = 12
#5y + 4z = -3

a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
b = np.array( [4, 12, -3] )

from numpy import linalg

linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [28]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

In [14]:
#Задание 4

users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ]

)

next_user_stats = np.array([0, 1, 2, 0, 0, 0])



In [26]:
for user_id, user_vector in enumerate(users_stats):

    def cosine(user_vector, next_user_stats):
        result = dict()
        # длины векторов
        aLength = np.linalg.norm( user_vector )
        bLength = np.linalg.norm( next_user_stats )
        cosine_ = np.dot( user_vector, next_user_stats) / ( aLength * bLength )
        return result.setdefault('user_id',cosine_ )


print(result)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
